output_dir: inferences/rankme_fineweb_15k_test

model_name: "EleutherAI/pythia-1b-deduped"
batch_size: 512
dataset_name: fineweb
num_samples: 15000
max_length: 512
min_length: 32
checkpoints: [9000, 12000, 15000]
packing: padded
token_selection: last
collect_final_acts: true
residual_hook_point: identity_head
collect_A: false
collect_G: false
storage_format: acts
